### ISSUE TITLE
ALAC/AIFF support

### ISSUE THREAD

**Issue by mainrs** [RustAudio/rodio#193]
Taken from the readme, rodio doesn't support ALAC file playback (the compressed lossless file format used by Apple). Would be nice to have this too! Not sure if there are any crates that decode the data though.

Since this is kind of related to the prior question about file support, is AIFF supported as well?

Thanks!

**Comment by jsomedon** [comment]
> about ALAC a cargo crate exist: https://crates.io/crates/alac

If I want to use that crate, should I try to implement `Source` trait using that crate?

**Comment by wxllow** [comment]
[Symphonia](https://github.com/pdeljanov/Symphonia) has an [ALAC decoder](https://github.com/pdeljanov/Symphonia/tree/master/symphonia-codec-alac#symphonia-alac-codec), is there any chance of ALAC support being added to Rodio using this?
