### ISSUE TITLE
The spatial example is broken

### ISSUE THREAD

**Issue by teknico** [RustAudio/rodio#197]
As of commit `a55cac7` the `spatial` example does not emit any sound. It was broken by part of #191.

**Comment by Xaeroxe** [comment]
Can you please provide more info on your platform? I can't reproduce this on Windows 10 64 bit with the MSVC toolchain.

**Comment by teknico** [comment]
I'm using Ubuntu 18.04. The fix is already merged (see above), to reproduce you have to revert it locally.

**Comment by Xaeroxe** [comment]
Ah okay thanks

**Comment by est31** [comment]
Seems fixed by 198
