### ISSUE TITLE
SineWave has growing levels of distortion over time because of float round off errors

### ISSUE THREAD

**Issue by mlindner** [RustAudio/rodio#207]
This is one of the two issues found in https://github.com/tomaka/rodio/issues/201.

There's random noise that creeps in as the float32 shifts exponent sizes as shown in the image below. The image below is a constant 3000 hz sine wave. In the top part of the image is a waterfall plot showing the growing frequency distortion spread as the float errors increase.

<img width="620" alt="float32 44100hz" src="https://user-images.githubusercontent.com/2280117/47970314-90fb9f80-e038-11e8-8a8b-a963abbcb69b.png">

**Comment by dvdsk** [comment]
Note: still an issue with new SignalGenerator however #202 no longer works. 

@iluvcapra as this is your baby :) do you have time and if so would you like to address this? No issues if you can not we can take care of it. For context see the last few messages in #202.

**Comment by iluvcapra** [comment]
Yeah I can take a look this week, it should be possible to just modulo t by the wavelength and that should resolve this I think.

**Comment by iluvcapra** [comment]
Check this out ☝️ I need to actually run it through an RTA to see if this is well and truly done but I think I've addressed the theoretical problem.

**Comment by dvdsk** [comment]
> Check this out ☝️ I need to actually run it through an RTA to see if this is well and truly done but I think I've addressed the theoretical problem.

very nice thanks for working on it :+1:, I left some feedback but I am no audio expert so I may very well be wrong!
