### ISSUE TITLE
Maintenance: Consider moving to an organization

### ISSUE THREAD

**Issue by azriel91** [RustAudio/rodio#227]
Hiya @tomaka,

Thank you for this crate -- it provides one of the fundamental capabilities to the Rust ecosystem. Wondering, would you be open to making `rodio` a community maintained project? If so, I'm thinking https://github.com/rustgd (~~though I have yet to ask, but they're not far away~~ ..and I've just joined).

**Comment by tomaka** [comment]
I wouldn't be against this, but the multitude of possible organizations it could be moved to makes it difficult to choose.

**Comment by azriel91** [comment]
Oh ya, the rustgd org members agree that [RustAudio](https://github.com/RustAudio) is more appropriate 🙂.

**Comment by erlend-sh** [comment]
There appears to be community consensus that RustAudio would be a good fit. azriel is part of the org so it can be moved via them.

**Comment by erlend-sh** [comment]
The community is in agreement that RustAudio would be the best home for rodio (and by extension cpal as well imo).

As a relative newcomer to the Rust ecosystem in recent years I’m in awe of your involvement with so many fundamental libraries @tomaka 👏 🙏 

As there’s only so much of you to go around, I’ve been thrilled to see the likes of winit/glutin mature into a more widely distributed community effort, driven forward by an organized team of core contributors.

I hope to see the same happen with rodio/cpal, and I’m confident it can, given how established and active the RustAudio community is.

**Comment by tomaka** [comment]
Done.

I don't really know how the RustAudio organization is organized, so I only gave write access to the people in the "Owners" team. Let me know if I should change that.

**Comment by est31** [comment]
@tomaka it's fine with me (one of the three people in that team). I personally think that rodio is a great addition to the RustAudio group of crates. The audrey crate which is a bit an alternative to this never really took traction, while this one is quite popular in the gamedev community (of which I'm a part too).

As for @mitchmindtree and @piedoom : are you fine with the move, as well?

**Comment by piedoom** [comment]
I think it's great!  It seems as though the pattern is to give owners permissions and then add collaborators or team members (of which tomaka is already a member on this project). So everything looks to be in order :) though I am unsure if it grants you the ability to add collaborators.

**Comment by azriel91** [comment]
Thank you very much :bowing_man:!
