### ISSUE TITLE
Use edition 2018?

### ISSUE THREAD

**Issue by alexheretic** [RustAudio/rodio#245]
Is this wanted? I'd be happy to raise the pr.

**Comment by est31** [comment]
Thanks. Personally I avoid edition 2018 for now. However, it would be great if you could run `cargo +nightly fix` on the codebase, as there seem to be some warnings on nightly.

**Comment by alexheretic** [comment]
Ok np for now. I think you should eventually, I like 2018 personally because I can only remember a single set of syntax rules at once.

**Comment by est31** [comment]
@alexheretic yes on a long term basis, I do want a switch to edition 2018. At some point, contributors might not be accustomed to older editions any more. But edition 2018 isn't even one year old yet.
