### ISSUE TITLE
Rodio does not include cpal::Format

### ISSUE THREAD

**Issue by tirz** [RustAudio/rodio#253]
**Context:**

I am writing a little lib in Rust to use rodio from a Java program.
Since rodio does not offer this kind of option, I need to encapsulate my needed structure:

```
use std::ops::Deref;

use rodio::Format as RodioFormat;

struct JodioFormat {
    format: RodioFormat,
}

impl From<RodioFormat> for JodioFormat {
    fn from(format: RodioFormat) -> JodioFormat {
        JodioFormat {
            format,
        }
    }
}

impl Deref for JodioFormat {
    type Target = RodioFormat;

    fn deref(&self) -> &Self::Target {
        &self.format
    }
}

trait Format {
    #[allow(non_snake_case)]
    fn getChannels(format: &JodioFormat) -> u16;
}

impl Format for JodioFormat {
    #[no_mangle]
    #[allow(non_snake_case)]
    fn getChannels(format: &JodioFormat) -> u16 {
        format.channels
    }
}
```

But rodio does not re-export cpal::Format. So I cannot recreate my own structure which will contain the Format.

**Fast fix:**

Add a dependency to cpal to Cargo.toml.

**Problem:**

This may lead to a compile error in the future.
If cpal::Format is updated, it will become incompatible with my version of rodio.
So I need to always be sure to keep a compatible version of cpal with my version of rodio => lead to pain.

**Solution:**

Re-export cpal::Format to rodio::Format.
With this fix, we do not need to include cpal for using the Format struct anymore... So we can be sure that our version of rodio::Format will always match with the cpal::Format version included to rodio.

**Comment by est31** [comment]
Fixed in #254
