### ISSUE TITLE
Increasing Volume without decreasing quality?

### ISSUE THREAD

**Issue by Who23** [RustAudio/rodio#260]
hello

I am trying to figure out how to increase the volume without decreasing the quality of the audio.

I've found that increasing it beyond 1.3x and 1.4x adds little crackles to the base, at least on my built in external speakers.

Is there any way to prevent this, or is it not really possible.

Thanks.

**Comment by Zizico2** [comment]
As I see it, the default volume "1" is the max volume. 0 is silent. The volume value should be kept between 0 and 1.

**Comment by Who23** [comment]
I see. That makes sense. Thanks!
