### ISSUE TITLE
Sound crackles when using Sink

### ISSUE THREAD

**Issue by Rua** [RustAudio/rodio#266]
When I play a sound using `Sink`, there is a slight crackling to be heard in the output, like very short interruptions in the sound. This crackling is not present if I play the same source directly via `play_raw`. In [src/sink.rs:90](https://github.com/RustAudio/rodio/blob/master/src/sink.rs#L90), if instead of submitting the source to `queue_tx`, I call `play_raw` directly, the crackling goes away (but of course that makes appending no longer work). So it seems to be related to the use of queues in `Sink`, but I don't know enough to investigate further.

I'm running Linux Mint 19.3.

**Comment by paulirotta** [comment]
See the similar discussion and possible work-around in #225
