### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by azriel91** [RustAudio/rodio#268]
Heya, may I request a new version of `rodio` to be published? I know it's only got 2 crate version bumps, but those would allow `amethyst` to not compile two versions of `nalgebra` (and transitive dependencies), which would be a nice present for myself :v:

**Comment by est31** [comment]
Your code depends on an outdated version of rodio: https://github.com/amethyst/amethyst/blob/45536af87974e5813cc6dbe757f0d8b3267e48dc/amethyst_audio/Cargo.toml#L28

The latest one is 0.10 and doesn't depend on nalgebra at all, see the changelog: https://github.com/RustAudio/rodio/blob/master/CHANGELOG.md

As for rodio's dependencies, I can't find any nalgebra in the rodio lockfile so I'd say they don't depend on nalgebra either.

That being said, we can absolutely publish a new version. Just wanted to set the facts straight.

**Comment by azriel91** [comment]
Oh ya, there is https://github.com/amethyst/amethyst/pull/2044 that bumps the `cpal` and `rodio` versions; simply wanted to have the latest of each.
