### ISSUE TITLE
I want to decode from the bytes in memory

### ISSUE THREAD

**Issue by sumibi-yakitori** [RustAudio/rodio#291]
I want to decode the sound from `include_bytes!`.
That doesn't seem to be possible since rodio currently requires a static lifetime to decode.
Why do we need a static lifetime for the decoder's generic parameters?   

```rust
let mut buf = Cursor::new(include_bytes!("example.ogg").to_vec());
let source = rodio::Decoder::new(&mut buf)?;
```

**Comment by est31** [comment]
Does removing the `&mut` work?

**Comment by sumibi-yakitori** [comment]
Oh, I'm sorry.
The code worked.
