### ISSUE TITLE
Audio skips a lot

### ISSUE THREAD

**Issue by dyc3** [RustAudio/rodio#305]
Whenever I play audio using this crate, the audio skips a lot, and playback is faster than normal. This only occurs when compiling unoptimized, with debug information. Compiling for release fixes the issue.

Using the example code in the docs:

```rust
let sink = Sink::new(&device);
let source = rodio::source::SineWave::new(440);
ink.append(source);
thread::sleep(Duration::from_millis(1000));
```

I'm using
Ubuntu 18.04
cargo 1.45.0 (744bd1fbb 2020-06-15)

**Comment by dyc3** [comment]
I've found that this only happens when I'm streaming or have another heavy load running.

**Comment by GiraffeKey** [comment]
Use `sink.sleep_until_end()`

**Comment by dyc3** [comment]
The issue still occurs using that function. I've found that this bug only occurs when I'm streaming. Looking at htop, it's using about 24% CPU when unoptimized, and only about 1% CPU when compiled in release mode.

**Comment by est31** [comment]
You can compile dependencies only in release mode.  https://doc.rust-lang.org/cargo/reference/profiles.html#overrides

IDK what rodio can do to improve this. If you have any ideas, PRs are welcome.
