### ISSUE TITLE
Rust files in examples folder does not work

### ISSUE THREAD

**Issue by cbondurant** [RustAudio/rodio#306]
I was inspecting the `/examples` folder of this repository to help figure out issues I was having with using the filters for rodio, and noticed that none of the examples correctly compile.

This seems to be because `OutputSink` and `rodio::Sink::try_new` do not exist. 

Im currently using the newest version of rodio: `0.11.0` on rust `1.41.0`

**Comment by est31** [comment]
@cbondurant yes the API will change in the upcoming release. Either depend on the git version of rodio, or use examples from the 0.11.0 release commit in this repo.
