### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by alexheretic** [RustAudio/rodio#321]
It'd be nice to have a new rodio release wrapping the newest cpal code. Rodio `0.11` issues may not apply to newer cpal releases.

I've been using master branch for Robo Instructus and it seems to work ok.

**Comment by est31** [comment]
Agreed, this is a good idea. Not sure why I haven't done a release right after the cpal update.

**Comment by est31** [comment]
I've created a 0.12 milestone here: https://github.com/RustAudio/rodio/milestone/1

**Comment by Rua** [comment]
I know someone is currently working on rewriting the `SampleRateConverter`, so if that works then that bug should be fixed.

**Comment by est31** [comment]
Reopening as travis CI seems to have been disabled for the org, and no crates.io publish key is available.

@tomaka I've created the `rustaudio/rodio-maintainers` team on github. Could you add it as owner of the crates.io crate? Then I could set up github actions CI auto publishing, or publish it manually.

**Comment by tomaka** [comment]
Done

**Comment by est31** [comment]
Thanks again! I've published 0.12 manually to get it out, but for future releases we should figure out how to migrate to Github actions and use @rustaudio-publish-bot.
