### ISSUE TITLE
Unnecessary Seek for decoders - prevents internet radio

### ISSUE THREAD

**Issue by pimdh** [RustAudio/rodio#333]
Hi,
Thanks for making this convenient library. I'm rather new to rust, so apologies if this question is inappropriate or irrelevant.

The Decoders currently require the data argument to implement the seek trait. However, the seek function appears to be only used for the LoopedDecoder, and by the is_wav() and is_flac() check functions. The underlying decoding libraries (except for the Vorbis decoder) do not require seek. 

I'm trying to work with internet radio that is a streamed MP3, for which it's hard/undesirable to implement a Seek trait. If I simply strip the seek trait from the Mp3Decoder, the following code works:
```
let url = "https://example.com/example.mp3";
let mut body = reqwest::blocking::get(url).unwrap();
let source = Mp3Decoder::new(body).unwrap();
let _res = stream_handle.play_raw(source.convert_samples());
```

Maybe the decoding check functions, the types and the trait bounds could be modified, so that the Mp3Decoder does not always require Seek on the data argument?

Thanks!

**Comment by est31** [comment]
You can try defining a custom type and just `panic!()` when the seek function is actually called.

**Comment by pimdh** [comment]
Okay thanks! I worked around it by just copying Mp3Decoder and removing the Seek trait bound.
