### ISSUE TITLE
Creating a large number of sinks causes crackling

### ISSUE THREAD

**Issue by Kl4rry** [RustAudio/rodio#337]
When creating more then about 25 sinks the audio becomes distorted and laggy.
This happens even if only one sink is actually playing audio.

**Comment by CleanCut** [comment]
First, are you running in `--release` mode?  Second, that's a large number of sinks!  This is _most likely_ just working as intended. From [the docs](https://docs.rs/rodio/0.13.0/rodio/#how-it-works-under-the-hood):

> All the sounds are mixed together by rodio before being sent to the operating system or the hardware. Therefore there is no restriction on the number of sounds that play simultaneously or the number of sinks that can be created (except for the fact that creating too many will slow down your program).

If you really want that many audio tracks playing simultaneously, you probably need a _hardware_
solution...or a library that uses dedicated sound hardware for mixing tracks, anyway.

**Comment by Kl4rry** [comment]
I may not have been using --release hover i don't remember because it was like 5 months ago. I cannot seem to recreate the problem in release mode so ty i guess

**Comment by CleanCut** [comment]
Great! It looks like this issue can be closed. 😄
