### ISSUE TITLE
Am I able to extract the frequencies using this library?

### ISSUE THREAD

**Issue by Joe23232** [RustAudio/rodio#346]
Hi, am I able to extract the frequencies using this library?

**Comment by est31** [comment]
@Joe23232 this library does not include a dct implementation but you can translate the time domain data that it does return using DCTs if you want :).

**Comment by Joe23232** [comment]
> @Joe23232 this library does not include a dct implementation but you can translate the time domain data that it does return using DCTs if you want :).

I see, thanks mate :)

I know that this is part of the Rust Audio group, do you know any other crate that may help with what I am after?
