### ISSUE TITLE
AAC + MPEG/AAC decoder

### ISSUE THREAD

**Issue by probablykasper** [RustAudio/rodio#351]
I made the crate [redlux](https://crates.io/crates/redlux) which decodes AAC, as well as AAC from MPEG-4 containers. It uses [fdk-aac bindings](https://crates.io/crates/fdk-aac) to decode AAC and [rust-mp4](https://crates.io/crates/mp4) to read the MPEG-4 containers.

If it's something that could potentially be used by rodio, feel free to. It already implements the `Source` trait.

It does have some potential [caveats](https://github.com/probablykasper/redlux#caveats) though, and to decode MPEG-4 files it needs to get the size of the file.

**Comment by est31** [comment]
Oh nice that's pretty cool! Generally, why not? I have some concerns with the fdk-aac bindings link. The -sys crate mentions the MIT license while vendoring the fdk-aac library which apparently has a custom (but open source, at least copyright wise) license.

I'm not sure about the patent situation though. It seems you'll need a license to distribute AAC decoders? If it's added to rodio it can't be turned on by default.

**Comment by probablykasper** [comment]
@est31 Yeah I had only briefly looked at the fdk-aac license.

I'm not really sure when you need a license. Many device manufacturers seem to be licensing AAC already, so does that mean you're good to go for playback on those devices since fdk-aac itself is open source?

[via-corp.com's AAC FAQ](https://www.via-corp.com/licensing/aac/aac-faqs/) says this:
> ### Who must sign a license?
> An AAC patent license is needed by manufacturers or developers of end-user encoder and/or decoder products.

Apparently the patents for LC-AAC expired over a year ago, but haven't found a good source to verify that.

**Comment by Shnatsel** [comment]
https://github.com/pdeljanov/Symphonia implements a pure-Rust LC-AAC decoder.

**Comment by aschey** [comment]
I have a branch with a Symphonia implementation working with basic functionality along with a few other changes such as seek support, although it's quite hacky and has some major caveats. [See this comment for more details.](https://github.com/RustAudio/rodio/issues/176#issuecomment-855505388)
