### ISSUE TITLE
Scrubbing

### ISSUE THREAD

**Issue by probablykasper** [RustAudio/rodio#372]
I'm looking to create a basic audio player, and for that I need to be able to move the play head to a time of the track, essentially scrubbing back or forwards within the currently playing track. I can't quite see how this could be done with rodio. Is it possible?

**Comment by dskleingeld** [comment]
There was some discussion before on this over here: https://github.com/RustAudio/rodio/issues/176. I have seeking working in a hackish way in a fork, that could work for you if you need an audio player for a hobby project?

**Comment by probablykasper** [comment]
@dskleingeld Thanks for letting me know about that! It is a hobby project, but would still want to be sure it's reliable.

A thing I would actually need is m4a support, which I've achieved so far by gluing together [fdk-aac c-bindings](https://crates.io/crates/fdk-aac) and rodio through my crate [redlux](https://crates.io/crates/redlux). I'm guessing for rodio to support seeking, the decoder has to support it. No idea how I'd manage that, hopefully there's a way :/
