### ISSUE TITLE
Question about crates implementing `Source`

### ISSUE THREAD

**Issue by probablykasper** [RustAudio/rodio#373]
I have a crate that implements the `Source` to be used with rodio. For that, I just specified rodio 0.13 as a dependency, which means that it now doesn't work with rodio 0.14.0.

What's the recommended way to go about this? Would it be safe to specify `0.*`, or should I publish a new patch that specifies  `>=0.13.0, <0.15.0`, or something else?

Related https://github.com/probablykasper/redlux/issues/3

**Comment by LiquidityC** [comment]
Can't you just re-export rodio through redlux. That would give users access to the version that redlux is built with?

**Comment by est31** [comment]
Oh wow I hadn't known about redlux. Great project! Ideally, rodio would depend on redlux, not the other way around. That's how it's done for the other formats as well. Willing to file a PR?

Also, if you want the `aac` crate name, I can give it to you if you want it.

**Comment by est31** [comment]
I think the best would be to bump rodio to 0.14 in redlux's Cargo.toml. `0.*` is very bad because a future version of rodio might cause the build to break. `>=0.13.0, <0.15.0` is safe, but I think a bit uncommon.

**Comment by probablykasper** [comment]
@LiquidityC Fair point, probably worth providing that as an alternative

@est31 Thanks for explaining, I'll go and bump rodio to 0.14
