### ISSUE TITLE
AAC tracks playing back at 2x speed

### ISSUE THREAD

**Issue by compenguy** [RustAudio/rodio#379]
Using the new symphonia backends, playing back an AAC track in an MP4 container yields 2x speed playback through rodio.  This behavior is not observed when playing the same track through the symphonia-play utility, nor is it observed when manually setting the rodio decoder to use redlux.

This may be a mismatch in the sample rate being reported to rodio for these tracks, as they all use SBR, and some additionally use PS, to allow (but not require) upconversion from a lower base sample rate to a higher rate.

**Comment by est31** [comment]
It might also be a channel number mismatch, with the source being mono but it being interpreted as interleaved stereo. cc @aschey

**Comment by aschey** [comment]
@compenguy can you provide a file to reproduce this? I've been using this on a bunch of m4a files and they've all worked fine.

**Comment by compenguy** [comment]
> It might also be a channel number mismatch, with the source being mono but it being interpreted as interleaved stereo. cc @aschey

The issue I'm observing is definitely not a mono/stereo issue.  AAC SBR tracks are also valid AAC LC tracks, and thus there are two different sample rates that can be reported for them - the sample rate when decoding in AAC LC mode and the sample rate after applying the SBR upconversion data.

**Comment by compenguy** [comment]
> @compenguy can you provide a file to reproduce this? I've been using this on a bunch of m4a files and they've all worked fine.

This issue reproduces on AacPlus (HE-AACv2) files which use SBR data to allow upconverting low sample rate streams to higher sample rates.

Let me know if this link doesn't work for you - the file should only be available for the next 48 hours.

https://a.tmp.ninja/PQMcvWRJ.m4a

**Comment by aschey** [comment]
Thanks, I was able to download the file and reproduce the issue. I'll try to take a look at this soon.

**Comment by est31** [comment]
Is the issue reproducible with the symphonia player? https://github.com/pdeljanov/Symphonia/tree/master/symphonia-play

If so, it's not a rodio bug. If not, it's a rodio bug :).

**Comment by compenguy** [comment]
> Is the issue reproducible with the symphonia player? https://github.com/pdeljanov/Symphonia/tree/master/symphonia-play

It does not reproduce with symphonia-play.  I talked to the symphonia developer, and they mentioned that symphonia-player gets the sample-rate information from the first decoded sample, rather than using the stated sample rate from the file metadata.  The file metadata seems to be reporting the upconverted sample rate, not the LC sample rate.

**Comment by aschey** [comment]
Thanks for investigating. I was able to confirm that using the sample rate from the `SignalSpec` fixed the issue. I can clean up my change and make a PR to fix this soon unless someone else wants to beat me to it.

**Comment by est31** [comment]
@aschey PRs welcome!
