### ISSUE TITLE
`total_duration` for Wav is not consistent with other implementations

### ISSUE THREAD

**Issue by a1phyr** [RustAudio/rodio#382]
Currently `WavDecoder`'s `total_duration` returns the remaining duration of the sound ([code](https://github.com/RustAudio/rodio/blob/f6bb97e0d32b81ad7dbd9d20e6b7dc32e23a658f/src/decoder/wav.rs#L115-L120)). This is not consistent with the rest of the crate, where the `total_duration` is stored at the beginning and always returns the same value.

However, I thing that the logical thing to do is to return the *remaining* duration, as it is generally the interesting information. Additionally, it would be consistent with how `Iterator::size_hint` and `ExactSizeIterator::len` work.

So we should decide what we prefer, document it, and make it consistent within the crate.

**Comment by est31** [comment]
I think if there is a correction, it's the wav decoder that should be changed. To me it feels that the less depends on state, the better. I'd be okay with a function that returns the current sample offset though.
