### ISSUE TITLE
How to enable playing m4a files

### ISSUE THREAD

**Issue by jim4067** [RustAudio/rodio#385]
m4a files are off by dfault so, how do I enable playing them. The example too for m4a files does not work.

**Comment by est31** [comment]
You need to enable the `symphonia-aac` feature.

**Comment by jim4067** [comment]
Hello 👋🏾. I'm sorry but how do I do this. 

When I enable the feature in my cargo.toml using `rodio = { version = "0.14.0", features = ["symphonia-aac"] }` I get this error 

```
error: failed to select a version for `rodio`.
    ... required by package `play-song v0.1.0 (/home/jim_4067/Documents/rustcode/play-song)`
versions that meet the requirements `=0.14.0` are: 0.14.0

the package `play-song` depends on `rodio`, with features: `symphonia-aac` but `rodio` does not have these features.


failed to select a version for `rodio` which could resolve this conflict
```
Is there something that I am missing or misunderstanding?

**Comment by est31** [comment]
@jim4067 yeah the version that uses symphonia is not released yet. You can use rodio [from git](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) however.
