### ISSUE TITLE
do_skip_duration  infinite loop

### ISSUE THREAD

**Issue by benmooo** [RustAudio/rodio#393]

**Comment by est31** [comment]
Do you have a description for me? Sorry but bug reports need actual descriptions.

**Comment by benmooo** [comment]
The problem is when skip_duration is longer than the 'source' itself, the do_skip_duration function will resolve to infinite loop. However, i checked the source code on both github and crates.io(rodio  v0.14.0 which is the latest release ),  and the differences are:

src/source/skip.rs 
https://github.com/RustAudio/rodio/blob/d40551db783420fa95e2ac5c2a76ca74647ab858/src/source/skip.rs#L38
the following three lines of code are missing :
        if frame_len == 0 {
            return;
        }
Then i  change the Cargo.toml file
from
ridio="0.14.0"
to 
rodio={git = "https://github.com/RustAudio/rodio/"}

bug fixed.

**Comment by est31** [comment]
Sounds like it's been fixed by #388 then. Closing because it's fixed on master.
