### ISSUE TITLE
minimp3 causes iOS app store rejection due to slice_deque use

### ISSUE THREAD

**Issue by alice-i-cecile** [RustAudio/rodio#400]
> Heads up, using the mp3 Bevy feature will cause your iOS app to get rejected because minimp3 depends on slice_deque which uses an internal API for memory allocation.

First reported in https://github.com/bevyengine/bevy/issues/3145, but I figured I'd toss it upstream for the `rodio` team to look at.

**Comment by est31** [comment]
Thanks for filing a bug! Outside of removing the mp3 feature entirely, it's not very actionable from the point of view of rodio. There are two better places for bugs:

* The [minimp3 repo](https://github.com/germangb/minimp3-rs). They can switch away from slice-dequeue as it [seems unmaintained](https://github.com/gnzlbg/slice_deque/issues/94).
* The [slice-deque](https://github.com/gnzlbg/slice_deque) crate which does the offending internal allocations in the first place. Of course, as it is unmaintained, it is possible that you won't receive much help from its maintainer.

**Comment by alice-i-cecile** [comment]
Great; I'll file it upstream on `minimp3` and close this out then.

**Comment by LiquidityC** [comment]
Minimp3 already has a bug filés for this issue from a few months back. I have now created a fork of slice_deque with the issue patched because so long has passed and dropped them a PR for this very issue. 😊

**Comment by LiquidityC** [comment]
For reference: https://github.com/germangb/minimp3-rs/pull/38
