### ISSUE TITLE
High CPU usage on Linux

### ISSUE THREAD

**Issue by tralph3** [RustAudio/rodio#402]
I'm seeing a lot of CPU usage by this library. Currently, I'm just playing an mp3 file with a single sink without anything fancy, just playing the file, and I'm getting around 13% usage:

https://i.imgur.com/JQ5SedV.png

If I make an optimized build, it improved a bit, but very little:

https://i.imgur.com/OtkXP0Q.png

Compare this to other music players (one of which is running through wine, and the other uses Python): https://i.imgur.com/rW1KaoP.png

Yeah, it's way too much. Any way to improve this?

**Comment by est31** [comment]
Does the same error occur with the rodio examples? Does it occur when using minimp3 directly? Furthermore, note that only release mode matters, as debug mode is often very slow.

**Comment by lieff** [comment]
Such CPU load looks like anomaly.
I've tried https://github.com/corporateshark/PortAMP and it shows 0% total load:

![image](https://user-images.githubusercontent.com/10080078/142763181-8fb6d2b5-d8c3-47fb-94fb-a73224645312.png)

Even here more than half load comes from openal/pulseaudio and not from decoding:

![image](https://user-images.githubusercontent.com/10080078/142763118-a0d2add3-0a68-4703-9586-728b36974a43.png)

You can try use perf top -p [pid] to see where the most CPU time is spent.

**Comment by est31** [comment]
It could be a bug in the program of the filer, maybe there is a thread in there that does busy waiting or something like that. Or it is a rodio bug. I can't know unless the filer helps with triage.

**Comment by tralph3** [comment]
It does happen with the examples. This was taken directly from the documentation, the only external crate here is rodio, and you can see all the code to the left. Note that this is an **optimized build**.

<img src=https://i.imgur.com/FKJGHhm.png></img>

**Comment by tralph3** [comment]
So I just made a program that only had a `loop {}` statement and the cpu usage is about the same. It seems to be caused by the loop.

**Comment by tralph3** [comment]
Ok, I just made an optimized build using `sink.sleep_until_end()` instead of loop and... yeah, night and day:

<img src=https://i.imgur.com/pMwOUsR.png></img>

Guess I'll close this now, rodio seems to be doing fine.
