### ISSUE TITLE
Default to Symphonia for MP3 decoding

### ISSUE THREAD

**Issue by Shnatsel** [RustAudio/rodio#409]
[Symphonia](https://github.com/pdeljanov/Symphonia) is already a supported backend for MP3 decoding in rodio, but it is not the default. I believe Symphonia MP3 decoder has matured, and it's time to switch to using it by default.

Currently rodio defaults to `minimp3` for decoding, which is written in C and causes a number of issues:

* Complicated cross-compilation
* Potential security issues due to C code being entirely unsafe
* iOS app store rejection (see #400)

[Symphonia](https://github.com/pdeljanov/Symphonia) has an MP3 decoder written in 100% safe Rust. The decoding performance is exactly on par with ffmpeg in my tests.

I have tested the correctness of Symphonia's MP3 decoder on over 50,000 real-world files created by a variety of encoders to ensure correct decoding and compatibility with the files found in the wild, which resulted in multiple fixes (see https://github.com/pdeljanov/Symphonia/issues/72, https://github.com/pdeljanov/Symphonia/issues/78, https://github.com/pdeljanov/Symphonia/issues/99). These fixes are going to ship in the upcoming v0.5 along with support for gapless playback for MP3 files.

With safety, performance and compatibility all being in great shape for Symphonia's MP3 decoder, I believe it is time to switch to using it by default instead of `minimp3`.

**Comment by est31** [comment]
Sounds like a plan! I don't really want to completely remove support for the C implementation as long as no extremely liberally licensed alternative exists though (MPL might be too strict for some people).

**Comment by Shnatsel** [comment]
At a glance, most integration issues between Rodio and Symphonia have been fixed (#379, #401). #405 still outstanding, but the current mp3 adapter doesn't expose the total duration either, so it's not a blocker.

**Comment by Shnatsel** [comment]
Symphonia v0.5 has now shipped with an extensively tested MP3 decoder (I've run over 500,000 MP3s through it alone, and compared the results to mpg123, libmad and ffmpeg).

This seems like a good time to switch!

**Comment by est31** [comment]
I've checked the code and it seems that if you enable the `symphonia-mp3` feature, it already is the default. What do you mean by making `symphonia` the default?

**Comment by est31** [comment]
Note that minimp3 is *also* behind a feature. Both are default off.

**Comment by Shnatsel** [comment]
Ah! I was under the impression that minimp3 was enabled by default, but it wasn't. This report is invalid then; but I'll open a new issue for switching to Symphonia v0.5

**Comment by Shnatsel** [comment]
Nevermind, I see you have updated to Symphonia v0.5 in git already.

**Comment by est31** [comment]
Actually I just checked the Cargo.toml and minimp3 is a default enabled feature, so there is something left to do, switching `symphonia-mp3` with `minimp3` in default.

**Comment by Shnatsel** [comment]
Is there any way I can help move this forward? It should be a rather trivial change.

**Comment by est31** [comment]
A PR would be welcome.
