### ISSUE TITLE
Exclude examples from crates.io package

### ISSUE THREAD

**Issue by aleokdev** [RustAudio/rodio#420]
Right now, the [crates.io package](https://crates.io/crates/rodio) weighs an astounding 7.41 MB. Most of it is composed of the example files found in the `examples/` directory. I think that [excluding these files](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) from the package would greatly help in reducing the size of the crate.

**Comment by est31** [comment]
PRs welcome!
