### ISSUE TITLE
Play audio from a slice

### ISSUE THREAD

**Issue by daniellga** [RustAudio/rodio#432]
Hi! I have all my audios decoded in a f64 slice. Could you give me a hint in how I can create a buffered `Source` from this slice to use in `Sink` to play audio?

Thanks!

**Comment by est31** [comment]
`SamplesBuffer` implements the Source trait: https://docs.rs/rodio/latest/rodio/buffer/index.html#example

You won't be able to use it with f64 samples though, as the trait is not implemented for f64: #196

I guess you'll have to implement `Source` manually on a newtype over slices and do the conversion internally. Alternatively, you can send a PR to implement `Source` for f64 too :)
