### ISSUE TITLE
Question: playing audio from an async stream

### ISSUE THREAD

**Issue by MikMuellerDev** [RustAudio/rodio#439]
Hello, I like rodio but am struggeling to play audio from a network stream.

## Problem
I have a stream of type `futures_util::StreamExt` which has been fetched using the reqwest crate.
The problem is that this stream does not support `Seek` and other traits required by rodio.
I tried buffering the stream, then playing it, but it leads to pauses during playing.
This is a live-stream so i cannot download the entire response but must play it in an iterator-like fashion.
I do not know how to convert this stream into a type which implements the required traits used by rodio.

Here is what this stream looks like:
```rust
let mut stream = reqwest::get(url).await.unwrap().bytes_stream();
```

The optimal solution would transform the stream and play it directly.

**Comment by JasonWei512** [comment]
I managed to stream network mp3:

https://github.com/JasonWei512/code-radio-cli

See `mp3_stream_decoder.rs` and `player.rs`.

Basically, you need to:

1. Remove the `Seek` trait bound in https://github.com/RustAudio/rodio/blob/master/src/decoder/mp3.rs
 
2. Use blocking reqwest:
``` rust
let response = reqwest::blocking::get(listen_url).unwrap();
let source = Mp3StreamDecoder::new(response).unwrap();  // The Mp3Decoder without `Seek` trait bound in step 1
let sink = rodio::Sink::try_new(&stream_handle).unwrap();
sink.append(source);
```

**Comment by MikMuellerDev** [comment]
Okay, thank you very much, I will soon give this a try :)

**Comment by MikMuellerDev** [comment]
Despite this issue being closed, i would like to thank you for your answer.
I too managed to get a successfully working program using your solution.
