### ISSUE TITLE
How to obtain the current playing time and position when rodio plays music files

### ISSUE THREAD

**Issue by yunfengwangluo** [RustAudio/rodio#457]
How to obtain the current playing time and position when rodio plays music files

At present, I want to try to build a simple music playing software,

Music playing software needs the most basic

"Total duration" of music files

Current play position "Play time position"

Jump to the specified position "Time Position"

I don't know how to get the "play time position" at present

Thank you for your help

**Comment by BastianHentschel** [comment]
Does the functionality in #510 fulfill the "Play Time Position"?
