### ISSUE TITLE
stopping rodio::sink stops it forever.

### ISSUE THREAD

**Issue by denizsincar29** [RustAudio/rodio#472]
let s is a rodio sink loaded with a file.
```
s.append(source);
//wait some time
s.stop();
s.append(anothersource); // doesn't play.
```
built on windows.

**Comment by goolord** [comment]
to be clear calling `s.play()` also does not appear to make the sink playback, nor is the `clear` method accessible to me, for some reason

**Comment by starua** [comment]
Maybe you should try call `s.play()`?

**Comment by dvdsk** [comment]
@denizsincar29  did you figure it out or do you need help?

**Comment by denizsincar29** [comment]
I think this was fixed long ago. If yes, this issue must be closed.
