### ISSUE TITLE
cpal 0.15 and rodio 0.17 plans

### ISSUE THREAD

**Issue by rparrett** [RustAudio/rodio#477]
Hello,

Just a friendly poke to ask what plans there may be for a release with cpal 0.15 in the near future. I recall someone mentioning that a release might be forthcoming after cpal updated.

Bevy 0.10 is due in the next week or so and it would be great to sync up.

**Comment by est31** [comment]
The update is non-trivial, see #470 . A PR would definitely help if you want it done quickly, because currently I'm quite busy with other things.

**Comment by rparrett** [comment]
Ah, thanks for pointing me at that PR.

**Comment by mockersf** [comment]
hello @est31 

We would be very interested on a new version of rodio with the various fixes and updates already ready, mostly #455 which fixes random inversion of stereo channels. Is there anything I can do to help prepare a release?

**Comment by est31** [comment]
@mockersf with #478 merged I think it should be very easy to do a release (upgrading cpal turned out to be easier than I thought). I am working on a PR.

**Comment by est31** [comment]
0.17.0 is out: #480

**Comment by mockersf** [comment]
thanks!
