### ISSUE TITLE
Log noise since v17

### ISSUE THREAD

**Issue by HHogg** [RustAudio/rodio#483]
Since upgrading to version 17, there's something logging noise coming out. 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/7130591/222855388-f11d472e-0fcc-404c-9a76-7aa3d2b3a0fd.png">

From some quick searching, these logs don't seem to be coming from rodio. I see v17 updated cpal, and the latest cpal updated a load of dependencies so I haven't followed it down the tree.

**Comment by est31** [comment]
Seems to be a symphonia issue: https://github.com/pdeljanov/Symphonia/blob/17ffc93ec7629e7b4133b3577f28b3e9efecd6b1/symphonia-core/src/probe.rs#L259

In general, crates might add logging as they wish. You can control which crate's logs are shown with the RUST_LOG environment variable. Say `RUST_LOG=my_app=debug cargo run` only enables logging for `my_app` for example.

**Comment by HHogg** [comment]
Thanks for the tip @est31  👍
