### ISSUE TITLE
NoDevice error on Windows when attempting audio playback

### ISSUE THREAD

**Issue by pieterdd** [RustAudio/rodio#490]
I created the following minimal program:

```rs
use std::io::{BufReader, Cursor};

use rodio::{Decoder, OutputStream, Source};

fn main() {
    let (_, stream_handle) = OutputStream::try_default().expect("Sound I/O failed");
    let file = BufReader::new(Cursor::new(include_bytes!("test.wav")));
    let source = Decoder::new(file).expect("Sound decoding failed");
    let converted_samples = source.convert_samples();
    stream_handle
        .play_raw(converted_samples)
        .expect("Sound playback failed");
}
```

On my Windows machine, `cargo run` produces the following output:

```
❯ $Env:RUST_BACKTRACE=1; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target\debug\tmp.exe`
thread 'main' panicked at 'Sound playback failed: NoDevice', src\main.rs:12:10
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\panicking.rs:64
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\result.rs:1790
   3: enum2$<core::result::Result<tuple$<>,enum2$<rodio::stream::PlayError> > >::expect<tuple$<>,enum2$<rodio::stream::PlayError> >
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\result.rs:1069
   4: tmp::main
             at .\src\main.rs:10
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\tmp.exe` (exit code: 101)
```

When I play back the sound file in VLC, it sounds perfectly fine. I'm assuming the error is thrown [here](https://github.com/RustAudio/rodio/blob/3d1a5ac54c75a4e6662f43b0996db10627f7dccd/src/stream.rs#L84). Am I using rodio correctly? Is this a bug?

**Comment by pieterdd** [comment]
I changed my original [documentation](https://docs.rs/rodio/latest/rodio/)-based approach to one based on this [example](https://github.com/RustAudio/rodio/blob/master/examples/music_wav.rs).

This works for me:

```rs
use std::io::{BufReader, Cursor};

fn main() {
    let (_stream, handle) =
        rodio::OutputStream::try_default().expect("Output stream failed to open");
    let sink = rodio::Sink::try_new(&handle).expect("Sink open failed");

    let file = Cursor::new(include_bytes!("test.wav"));
    sink.append(rodio::Decoder::new(BufReader::new(file)).expect("Decode failed"));
    sink.sleep_until_end();
}
```

If anyone stumbles upon this thread through a search engine later, I'm not entirely sure why yet but that should do the trick!

**Comment by FoxLoveProgramming** [comment]
I'm sorry for my English... let (_, stream_handle), _ has a very short lifespan and is only valid in the current statement, so rust releases the OutputStream, resulting in no devices behind, and let (_tmp, stream_handle) will work fine. Because Rust thinks that _tmp lifecycle isn't just in the current statement, it's just that there are unused tags

**Comment by FoxLoveProgramming** [comment]
I'm sorry for my English... let (_, stream_handle), _ has a very short lifespan and is only valid in the current statement, so rust releases the OutputStream, resulting in no devices behind, and let (_tmp, stream_handle) will work fine. Because Rust thinks that _tmp lifecycle isn't just in the current statement, it's just that there are unused tags

**Comment by pieterdd** [comment]
Good to know, thanks!
