### ISSUE TITLE
i Cannot to clone() rodio::Sink

### ISSUE THREAD

**Issue by manaim2112** [RustAudio/rodio#509]
`
#[tauri::command]
fn play_audio(src: &str, alarm: State<Alarm>) -> bool {
    let (_stream, stream_handle) = OutputStream::try_default().unwrap();
    let sink = match Sink::try_new(&stream_handle) {
        Ok(s) => s,
        Err(_) => return false,
    };

    let open = match File::open(src) {
        Ok(r) => r,
        Err(_) => return false,
    };

    let file = BufReader::new(open);
    let source = Decoder::new(file).unwrap();

    let mut ctx = alarm.sink.lock().unwrap();
    if let Some(old_sink) = ctx.take() {
        old_sink.stop();
    }
    sink.append(source);
    *ctx = Some(sink.clone());
    sink.sleep_until_end();
    true
}
`

i have problem sink cannot clone() in *ctx

**Comment by BastianHentschel** [comment]
Sink doesn't implement the trait Clone, so you can't clone it.

If you need shared mutable access you might consider an Arc<Mutex<>> around it.
