### ISSUE TITLE
Reverb example rans into error with symphonia vorbis decoder 

### ISSUE THREAD

**Issue by dvdsk** [RustAudio/rodio#516]
Probably belongs upstream in symphonia, ran into it testing #513. 

seems like `assets/music.ogg` breaks the decoder.

Needed it documented somewhere so here it is. Reproducible on master branch with:

```
cargo r --example reverb --features symphonia-all
```

**Comment by est31** [comment]
It's not hard to test if the culprit is symphonia: symphonia probably also has examples in their own repo. And if not, there is probably some symphonia user one could try.

**Comment by dvdsk** [comment]
replicated upstream, moving this issue there.

see: https://github.com/pdeljanov/Symphonia/issues/235

**Comment by dvdsk** [comment]
Issue is on this side, I'm working on it. Expect a PR sometime this week.
