### ISSUE TITLE
Decoder::skip_duration consumes the object (self, not &self)

### ISSUE THREAD

**Issue by DoormatIka** [RustAudio/rodio#524]
![image](https://github.com/RustAudio/rodio/assets/68234036/efbc9090-0be1-48e8-8fc0-9d74a4a9fe45)

Good evening, this function consumes the Decoder object, making it unusable to append to.

**Comment by dvdsk** [comment]
It consumes the Decoder and [produce something](https://docs.rs/rodio/0.17.3/rodio/source/trait.Source.html#method.skip_duration) that implements Source, specifically a [SkipDuration](https://docs.rs/rodio/0.17.3/rodio/source/struct.SkipDuration.html#impl-Source-for-SkipDuration%3CI%3E). You can do the same with a source as you can with a decoder.

Its similarly to how iterators work (see [take](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take)).

**Comment by dvdsk** [comment]
Hey @DoormatIka are you still stuck? If not could you close this Issue?

**Comment by DoormatIka** [comment]
I'll close it. My apologies for not responding 😅
