### ISSUE TITLE
Entire system sound mutes while debugging

### ISSUE THREAD

**Issue by ValonInc** [RustAudio/rodio#530]
Hello everyone,

my entire system sounds mutes every time I debug a program after a `OutputStream` has been created.

Example program:
```rust
use std::time::Duration;
use rodio::{OutputStream, Sink};
use rodio::source::{SineWave, Source};

fn main() {
    let (_stream, stream_handle) = OutputStream::try_default().unwrap();
    let sink = Sink::try_new(&stream_handle).unwrap();

    let source = SineWave::new(440.0).take_duration(Duration::from_secs_f32(60.0)).amplify(0.15);
    sink.append(source);

    sink.sleep_until_end();
}
```

I have no sound at all, when I debug after the second line of code in main `let sink = ...`.
The sound reappears after I halt the program or continue running it.

My expectation is that at least other programs (like Firefox) on my system are able to output Sound.

I'm using Rodeo 0.17.3
in RustRover 2023.3
on Ubuntu 23.10

Please tell me if anybody needs more Information.

Notes:
The "Volume Levels" under Settings>Sound>"Volume Levels" still show that Firefox is "Outputing" Sound.

**Comment by dvdsk** [comment]
what do you mean with debug? do you mean attach with gdb?

**Comment by ValonInc** [comment]
I was able to confirm this with gdb.

`rust-gdb target`
`b main.rs:12`
`r`

I dont actually know what RustRover does.

**Comment by dvdsk** [comment]
strange, I can not reproduce it on Pop!_OS 22.04 LTS.  Though pop uses pipewire that could have something to do with that.

Could you post the output of `pactl info | grep "Server Name"`?

and could you try with the cpal [beep example](https://github.com/RustAudio/cpal/blob/master/examples/beep.rs)? 
A breakpoint at https://github.com/RustAudio/cpal/blob/2ec761d30b35dbbacfecb41a2f5985781a7d52d1/examples/beep.rs#L123 should do the same as one at sink.sleep_until_end() in your example.

**Comment by dvdsk** [comment]
That means its an issue in `RustAudio/cpal`. I took a look yesterday and this is not reported there yet. If its important too you I suggest you report it there. I will have to close this issue as we can not do anything here to solve it. Thanks for the report though!
