### ISSUE TITLE
Is there way to add silence to end of source to make it a certain length?

### ISSUE THREAD

**Issue by dexterdy** [RustAudio/rodio#534]
As per the title. I am building a small audio looping application, for which it is very crucial to be able to make sounds play in cycles of some duration, often longer than their own length. Example: play a 2 second sound effect every 15 minutes. Is there a convenient way in which I can add silence to the end of a source to fill it to a certain duration?

I am already using `take_duration`, which can be used if the desired loop has a length shorter than the source length (loop the first 5 mins of a 10 min source), but it does not add silence to the end if the entered duration is longer than the length of the source.  

I am essentially looking for the combined behavior that does both of these with a single parameter: when the cycle should end. Does something like that exist?

**Comment by dexterdy** [comment]
I will answer my own question:

```rust
let silence: Zero<i16> = Zero::new(decoder.channels(), decoder.sample_rate());
let decoder_padded = decoder.mix(silence);
let decoder = decoder_padded.take_duration(my_duration);
```

**Comment by est31** [comment]
Closing this as the question is answered. If you disagree, please write.
