### ISSUE TITLE
Sound cannot be played if OutputStream is unused

### ISSUE THREAD

**Issue by istudyatuni** [RustAudio/rodio#555]
```rs
// this works
let (_stream, handle) = OutputStream::try_default()?;
// this doesn't
let (_, handle) = OutputStream::try_default()?;
```

In second case `Sink::try_new(&handle)` returns `NoDevice` error. Perhaps this should be mentioned in the docs? I've spent a lot of time trying to figure out what's wrong.

**Comment by dvdsk** [comment]
Underscore is actually not a valid identifier. Its a pattern that matches everything and throws it away. You are effectively dropping (and thus closing) the output-stream at the end of the line.

Here are some docs (its not really explained in the book I think).

- https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html?highlight=underscore#ignoring-an-entire-value-with-_
- https://doc.rust-lang.org/stable/reference/patterns.html?highlight=single%20underscore#wildcard-pattern
- https://doc.rust-lang.org/stable/reference/identifiers.html?highlight=underscore#identifiers
