### ISSUE TITLE
Should `Decoder` be cached?

### ISSUE THREAD

**Issue by feois** [RustAudio/rodio#583]
Context: I am trying to create a music player

IDK how is it implemented internally, is it inefficient to use new `Decoder` every time thus the need of caching or is it completely fine?

**Comment by dvdsk** [comment]
whats the context? Do  you need multiple decoder's for a single audio file?

**Comment by dvdsk** [comment]
Ahhh, I understand now. In the context of a music player you need not worry about it. Depending on the codec the decoder might do some IO on creation but that is quite quick and should not be a problem.

**Comment by feois** [comment]
> Ahhh, I understand now. In the context of a music player you need not worry about it. Depending on the codec the decoder might do some IO on creation but that is quite quick and should not be a problem.

Thanks for the helpful reply!
