### ISSUE TITLE
Seek support for flac

### ISSUE THREAD

**Issue by JamieH01** [RustAudio/rodio#586]
It appears that flac lacks seeking support. Would this be possible/planned in the future? This is currently whats stopping me from using this.

**Comment by dvdsk** [comment]
by default rodio claxon for flac decoding. If you switch to the symphonia backend you'll get seeking :)

`rodio = { version = "some version", features = ["symphonia-flac"] }`

**Comment by dvdsk** [comment]
in the future I hope to make the symphonia backends the default since they support the most features. That might be a breaking change so that will be shipped at the same time as when we overhaul the features.

**Comment by JamieH01** [comment]
oh! thank you!

**Comment by JamieH01** [comment]
i apologize for the spam issue, i was under the impression that the flac support was enabled by default. maybe just me missing something, but maybe that could be made more clear in the docs?

**Comment by dvdsk** [comment]
> i apologize for the spam issue, i was under the impression that the flac feature that was enabled by default was the only one. maybe just me missing something, but maybe that could be made more clear in the docs?

no worries, it is a bit unclear right now. I hope to enable the easier decoder (symphonia) by default in the future but that is a breaking change so it takes a bit of coordination to make sure we dont break ppls code tooo much :)

meanwhile you should feel free to clarify the docs, documentation PR's are always welcome :)
