### ISSUE TITLE
No working if only sink is kept after constructing

### ISSUE THREAD

**Issue by chanmaoganda** [RustAudio/rodio#599]
``` rust
pub fn new() -> Self {
  let (_stream, stream_handle) = OutputStream::try_default().unwrap();
  let sink = Sink::try_new(&stream_handle).unwrap();
  Self {sink}
}
```

If i try to use the struct only keeping `sink`, it is unable to play any music

**Comment by chanmaoganda** [comment]
Perhaps it is better to mention that?

**Comment by dvdsk** [comment]
it will be in the next release: https://github.com/RustAudio/rodio/pull/591
and I hope to remove the need for keeping the stream in the future
