### ISSUE TITLE
How do I obtain the current channel index/detect when I'm back at channel zero in a stream?

### ISSUE THREAD

**Issue by iluvcapra** [RustAudio/rodio#603]
A source implementation question:

If I call `next()` on a source and its channel count is > 1, how do I tell which channel number the sample it returns is for?

**Comment by dvdsk** [comment]
you have to keep track of that yourself unfortunately. Some details of how the channel numbering maps to speakers can be found here: https://github.com/RustAudio/rodio/pull/559

**Comment by iluvcapra** [comment]
But if like, I get a Source, is the first sample of the iterator or each frame guaranteed to be channel zero? 

Or like if I enumerate an iterator with the sample count, with the count modulo the channel count always give me the channel index of this sample?

The API doesn't seem to guarantee that, at least `skip` and `take` don't seem to.

**Comment by dvdsk** [comment]
> But if like, I get a Source, is the first sample of the iterator or each frame guaranteed to be channel zero?

As I understand it, [yes](https://learn.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatextensible). Rodio sources should take care to preserve sample order, so no matter how much you wrap something the first sample should always be the same as if you read directly from the decoder.

> The API doesn't seem to guarantee that, at least skip and take don't seem to.

Can you link to the docs of the API's that you mean?

> Like try_seeks doesn't seem to be guaranteed to always land at a frame boundary (frame in the conventional sense, and array of simultaneous samples one for each channel).

try_seek has a [test](https://github.com/RustAudio/rodio/blob/4805661cd1aa26c98129cd15cd8e98e821c4d30e/tests/seek.rs#L119) to check this behavior. If you can break that it is a bug.

**Comment by iluvcapra** [comment]
This is great thanks, I think I just needed to talk it through. I have a bunch of surround sound stuff I wanted to add.
