### ISSUE TITLE
Example on how to play a mono sound through a specific output channel

### ISSUE THREAD

**Issue by FinitelyFailed** [RustAudio/rodio#604]
Hi,

Sorry if this i not the correct place to ask. If it is not please redirect me to the correct place.

I'm trying to play a audio file, which is mono, on a specific output channel. How do I do that? I have only found simple examples. Which doesn't really tell me how to manipulate the pipeline in a more complex way.

Thanks.

**Comment by dvdsk** [comment]
take a look at the [`Source`](https://docs.rs/rodio/latest/rodio/source/trait.Source.html) trait, its analogous to `Iterator` in the std. You can use that to manipulate the audio stream. Note how source depends on iterator.

For your use case you want to make an struct (call it something like SkipChannels?) that implements Source and Iterator. Your struct have a field called inner that is generic over some `Source`.  Whenever next is called on your object you:
 - either call next on inner
 - return zero

Note Source also requires your object to have a method `channels()`. It should return the number of channels your output has. So if you only want the left speaker in a stereo setup `channels()` should return.

If you time when you return zero and when you call next correctly you will get audio on only one channel.

**Comment by dvdsk** [comment]
> I have only found simple examples.

Good point, if you get this working, could you make a PR adding it as a new example? I'll help refine it if needed.

**Comment by FinitelyFailed** [comment]
Thanks, I'll will try that.


> > I have only found simple examples.
> 
> Good point, if you get this working, could you make a PR adding it as a new example? I'll help refine it if needed.
Yes, of course. I'll will try to make a small example of it, if I get it working. :)

**Comment by dvdsk** [comment]
Did it work out? If it did not let me know we can reopen the issue and work on it together, maybe through a draft PR adding an example.
