### ISSUE TITLE
`panicked` when trying to play a `Sink` with reverb effect: `attempt to subtract with overflow`

### ISSUE THREAD

**Issue by setoelkahfi** [RustAudio/rodio#609]
I'm trying to add a reverb effect following [this example](https://github.com/RustAudio/rodio/blob/master/examples/reverb.rs), but `panic` when trying to play the sink. 
```bash
thread '<unnamed>' panicked at /feelslikehome/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.19.0/src/conversions/channels.rs:100:13:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: Rust panics must be rethrown
```
This is what I did:
```rust 
        // this is a function that returns (Mode, Sink, Stream) tuple
        match Decoder::new(BufReader::new(file)) {
            Ok(decoder) => {
                let mode = get_mode(path);
                if mode == Mode::Bass {
                    // Duration is just an arbitrary number
                    let reverb = decoder.buffered().reverb(Duration::from_secs(30), 1.0);
                    sink.append(reverb);
                } else {
                    sink.append(decoder);
                }
                sink.pause();
                Some((mode, sink, stream))
            }
            Err(e) => {
                info!("Failed to create decoder: {:?}", e);
                None
            }
        }
```

I suspect calling the `buffered()` is the problem, but it is needed because the reverb requires `clone`-able source. There's no API to `unbuffered` the decoder. When I tried to play the sink right away, it was also `panic`.

Any pointers?

**Comment by dvdsk** [comment]
This must be a bug. 

I do not see any disclaimers in the API docs and you only use rodio API's and do not implement a source yourself.

The panic you got points here: https://github.com/RustAudio/rodio/blob/6bfd840de6ee786ca7e06d21fd29fc888ddfa7fe/src/conversions/channels.rs#L100 which is the channel converter (for going from stereo to 5.1 or reversed). 

That has been improved a few months ago, could be a bug snug in there.

looking at that piece of code it can underflow:
```rust
fn size_hint(&self) -> (usize, Option<usize>) {
	let (min, max) = self.input.size_hint();

	let consumed = std::cmp::min(self.from, self.next_output_sample_pos) as usize;
	// comsumed can be 0;
	let calculate = |size| {
		// size can be zero => size + consumed can be 0
		(size + consumed) / self.from as usize * self.to as usize
		// 0 - nonzero => attempt to subtract with overflow
			- self.next_output_sample_pos as usize
	};

	let min = calculate(min);
	let max = max.map(calculate);

	(min, max)
}
```

The question: is it a bug when `self.next_output_sample_pos` is larger then zero when size and consumed are zero? 
- if yes: we have to fix that.
- if no: replace the `-` with a `..saturating_subtract(..)` and it should be fixed.

If you're willing to help you could put some strategic `dbg!()` in a local copy of rodio and see what is happening. If you do not have time no worries ill get to it someday though that could take a while.... :sweat_smile:

**Comment by setoelkahfi** [comment]
I put a `print` statement, and the example ran successfully only once. Then, it's the same error for the subsequent run.

Output:
```bash
    Finished dev [unoptimized + debuginfo] target(s) in 2.92s
     Running `target/debug/examples/reverb`
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
/// until it stops
```
Changes:
```rust
    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        let (min, max) = self.input.size_hint();
        print!("{}", self.next_output_sample_pos);
        ....

```

**Comment by dvdsk** [comment]
make a local clone of rodio. Setup your toml such that rodio is compliled from that path then change channels.rs in the local clone such that:

```rust
(size + consumed) / self.from as usize * self.to as usize
	- self.next_output_sample_pos as usize
```
becomes
```rust
((size + consumed) / self.from as usize * self.to as usize).saturating_sub(self.next_output_sample_pos as usize)
```

**Comment by setoelkahfi** [comment]
Now it doesn't `panicked`. I can open a PR.

**Comment by dvdsk** [comment]
I got some time and I am trying to reproduce the issue:

```rust
use rodio::Source;
use std::io::BufReader;
use std::time::Duration;

fn main() {
    let (_stream, handle) = rodio::OutputStream::try_default().unwrap();
    let sink = rodio::Sink::try_new(&handle).unwrap();

    let file = std::fs::File::open("assets/music.ogg").unwrap();
    let source = rodio::Decoder::new(BufReader::new(file)).unwrap();
    let with_reverb = source.buffered().reverb(Duration::from_secs(30), 1.0);
    sink.append(with_reverb);

    sink.sleep_until_end();
}
```

This does not reproduce it however. Could you try that on your machine? Does it panic there? Can you adjust it so that it does panic if it does not?

**Comment by setoelkahfi** [comment]
@dvdsk It doesn't panic anymore. I tried the example and the one in my code.

**Comment by dvdsk** [comment]
> @dvdsk It doesn't panic anymore. I tried the example and the one in my code.

and that is with the normal (git) version of rodio without the modifications we discussed above?

**Comment by setoelkahfi** [comment]
Yes.
