### ISSUE TITLE
add a simple overdrive effect

### ISSUE THREAD

**Issue by setoelkahfi** [RustAudio/rodio#611]
I want to implement a simple overdrive effect for a sink like [this example](https://rickyhan.com/jekyll/update/2018/02/06/rust-guitar-pedal-effects-dsp.html)? How do you think I should start?

I have copied the `Amplify` implementation but cannot make progress implementing the `process_samples` function from the example link. Something like this:

```rust
#[derive(Clone, Debug)]
pub struct Overdrive<I> {
    pub input: I,
    pub bypassing: bool,
    pub factor: f32,
}


impl<I> Iterator for Overdrive<I>
where
    I: Source,
    I::Item: Sample,
{
    type Item = I::Item;

    #[inline]
    fn next(&mut self) -> Option<I::Item> {
        self.input.next().map(|value|  {
            // I think I should modify the samples here but don't know how to get the array of samples.
            process_samples(value) 
        })
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.input.size_hint()
    }
}

```

Any pointers?

**Comment by dvdsk** [comment]
please let me know if this can be closed
