### ISSUE TITLE
Write contributor guide

### ISSUE THREAD

**Issue by dvdsk** [RustAudio/rodio#623]
Should explain implementation details such as:

- should I cast `Source<Item>` to `f32` if I need that, or demand `Source<Item=f32>`
- You run the benchmarks with `cargo bench`.

**Comment by UnknownSuperficialNight** [comment]
Just a list of things I can think of that we could look at when making a contributor guide (These are merely just a list of common things we can pick and choose from, I don't mean we need every single one of these)

# Rodio Contributor Guide
1. Introduction to Rodio
2. Getting Started
   - Prerequisites (Rust version, dependencies)
   - Setting up Rodio for development
3. Project Structure
   - Overview of main modules and their purposes
4. Coding Standards and Best Practices
   - Rust-specific guidelines
   - Rodio-specific conventions
5. Audio Processing Implementation Details
   - Handling different audio formats
   - Working with Source<Item> types
     - When to cast Source<Item> to f32
     - When to use Source<Item=f32>
   - Implementing new audio effects or sources
6. Testing
   - Writing unit tests for audio processing functions
   - Integration tests for playback
7. Benchmarking
   - Running benchmarks with `cargo bench`
   - Guidelines for writing performance-sensitive code
8. Documentation
   - Inline code documentation
   - Updating the Rodio API docs
   - Contributing to user guides or examples
9. Version Control and Contribution Workflow
   - Git branching strategy
   - Commit message format
   - Pull request process
10. Cross-platform Considerations
    - Handling platform-specific audio backends
11. Debugging Tips
    - Common issues and their solutions
    - Tools for audio debugging
12. Performance Optimization
    - Tips for efficient audio processing in Rust
13. Community Guidelines
    - Code of Conduct
    - Where to ask for help
14. Frequently Asked Questions
15. Additional Resources
    - Links to Rust audio programming resources
    - Relevant audio processing papers or articles

**Comment by dvdsk** [comment]
If you could write a draft (just leave everything you do not know/wanna write open) that would be nice. Then we can iterate on it as we go.

**Comment by UnknownSuperficialNight** [comment]
> no, just a draft for the contributers guide. Since the guide can not break anyone's code there is no reason to finish it before merging right? Even a partial guide can be useful already.

OK no problem, here is a very rough first draft

[CONTRIBUTING.md](https://github.com/user-attachments/files/17244473/CONTRIBUTING.md)

**Comment by dvdsk** [comment]
very nice, you can make a PR if you wish (you don't have to I can copy it in. I prefer PR's because it gives the contributor the credit they deserve.
