### ISSUE TITLE
Total Duration after speed up calculation is faulty

### ISSUE THREAD

**Issue by ugochukwu-850** [RustAudio/rodio#628]
After a speed increase the total duration tends to increase instead of decrease and vice versa .
I believe a change to the total_duration function  ,on the speed.rs module , to divide by factor instead of multiply by factor , would solve this .

Correct me if I am wrong

**Comment by dvdsk** [comment]
you are completely right, that should be a division! Good catch. If you want you can make a PR fixing it. Otherwise I'll fix it on main.

**Comment by ugochukwu-850** [comment]
Great 😊.
I have already fixed that .
I would raise the PR tomorrow.
I am to tired rn to mess with git ( I made the commit on a branch I was working on for another PR) .

**Comment by dvdsk** [comment]
> I am to tired rn to mess with git

I feel you, im trying to figure out how to edit a pr right now I should probably go to bed instead :yawning_face:
