### ISSUE TITLE
The use case of disabling feature `symphonia` is not fully covered

### ISSUE THREAD

**Issue by Patchethium** [RustAudio/rodio#635]
## Problem
When use
```toml
[dependency]
rodio = {version = "0.20.0", default-features = false, features = ["wav", "hound"]}
```
and disable dependency `symphonia`, rustc will throw
```
error[E0599]: no variant or associated item named `SymphoniaDecoder` found for enum `SeekError` in the current scope
   --> /home/.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/rodio-0.20.0/src/source/mod.rs:639:20
    |
590 | pub enum SeekError {
    | ------------------ variant or associated item `SymphoniaDecoder` not found for this enum
...
639 |         SeekError::SymphoniaDecoder(source)
    |                    ^^^^^^^^^^^^^^^^ variant or associated item not found in `SeekError`
```
## Solution
By adding a line `#[cfg(feature = "symphonia")]` at [here](https://github.com/RustAudio/rodio/blob/be29a3f0fdac4183fba6fa23dc0a885362d64ec9/src/source/mod.rs#L637), this error can be suppressed.

**Comment by dvdsk** [comment]
on it, will be fixed within the hour

**Comment by dvdsk** [comment]
new version published broken one is yanked (made unavailable) :+1: 

If 0.20.1 still has the issue (it should not) please re-open this
