### ISSUE TITLE
[macOS] Compiling with flutter bridge fails: unresolved symbols

### ISSUE THREAD

**Issue by vongohren** [RustAudio/rodio#659]
Hi! Really great library, so thanks for the effort.

Im currently testing this out with flutter_bridge and it fails with the following error. 
Im only reaching out here because the owner of the library refers to the main library quite often to handle the issue, and maybe you guys can assists in guiding this issue further? I have added some links to similar issues where this referral has happend.

https://github.com/fzyzcjy/flutter_rust_bridge/issues/2104
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1835
https://github.com/fzyzcjy/flutter_rust_bridge/issues/2267
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1610

Im new to rust so not sure where to take this and what might be wrong. 

```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-000478920A92401E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006000-000478920A92401E, name:My Mac }
Undefined symbols for architecture arm64:
  "_AudioComponentFindNext", referenced from:
      coreaudio::audio_unit::AudioUnit::new_with_flags::h76009ca9b63fea1a in librust_lib_my_app.a[arm64][342](coreaudio-7ea10ab24f7a2cb5.coreaudio.7ebb80c1a253ca2d-cgu.4.rcgu.o)
  "_AudioComponentInstanceDispose", referenced from:
```

# Questions
Are there any magic needed to compile this lib on macOS?
Should the things done in this issue: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1835 be enough? If so I just need to get some proper rebuild because after adding the frameworks, it still fails with same issue

**Comment by dvdsk** [comment]
all our platform specific code is in the cpal dependency. If you get cpal to build then rodio should work without an issue. 

I had a quick look and it seems like cpal on mac/ios uses coreaudio with is provided by coreaudio-rs. That in turn uses coreaudio-sys and it needs to be told where to it can find the MacOS SDK during build. That is done by setting a flag, see [coreaudio-sys](https://crates.io/crates/coreaudio-sys) for details.

If that does not work then that https://github.com/fzyzcjy/flutter_rust_bridge/issues/1835 might very well work.

**Comment by dvdsk** [comment]
is it compiling that fails or running? To me this `Launching lib/main.dart on macOS in debug mode...` sounds like it starts to run.

**Comment by vongohren** [comment]
Sorry for the late reply but I can confirm that it worked with whta was proposed in the issue you linked as well.

The main problem I had after adding the frameworks was a build cache not cleaning and not using the new frameworks. A simple delete of the build folder fixed that.

Sorry for taking your time, but thanks for confirming that it was the same dependencies, so it should not be a problem
