### ISSUE TITLE
music_ogg crashes on mipsel alsa taget

### ISSUE THREAD

**Issue by psych0d0g** [RustAudio/rodio#66]
./music_ogg 

> thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument"', ../src/libcore/result.rs:688

might be related to https://github.com/tomaka/cpal/issues/97

**Comment by est31** [comment]
Original issue [has been closed](https://github.com/RustAudio/cpal/issues/97#issuecomment-504592402), so will close this one too.
