### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by realroot2185** [RustAudio/rodio#662]
I tried to use rodio in an app.
No audio stream was shown in pwvucontrol, no audio and no error.

I tried an example and I had the same.
```
cargo run --example  music_ogg 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/music_ogg`
```

```
OS: Artix Linux x86_64
Kernel: Linux 6.12.4-artix1-1
Rodio: 0.20.1
```

**Comment by PetrGlad** [comment]
Does the program exit in a while (~70 seconds)? 
If there are no errors shown, that means at least the output device was opened successfully. I think that a wrong output device was opened. The default output constructor opens one of available output devices preferring system's default, it may not be the one you're expecting.

I assume you are using pipewire. Rodio will use ALSA interface (on Linux it is either ALSA or Jack), and pipewire should have a plugin for ALSA (it is normally installed by default).

You can check the defaults on the rodio side with
```rust
dbg!(&cpal::default_host().id());    
dbg!(&cpal::default_host().default_output_device().unwrap().name().unwrap());
```
Unfortunately rodio does not show any diagnostic messages when a non-default device is chosen.

**Comment by realroot2185** [comment]
Yes it exits after a while.
Yes I am using pipewire.
pipewire-alsa was not installed

**Comment by dvdsk** [comment]
> Does the program exit in a while (~70 seconds)? If there are no errors shown, that means at least the output device was opened successfully. I think that a wrong output device was opened. The default output constructor opens one of available output devices preferring system's default, it may not be the one you're expecting.
> 
> I assume you are using pipewire. Rodio will use ALSA interface (on Linux it is either ALSA or Jack), and pipewire should have a plugin for ALSA (it is normally installed by default).
> 
> You can check the defaults on the rodio side with
> 
> ```rust
> dbg!(&cpal::default_host().id());    
> dbg!(&cpal::default_host().default_output_device().unwrap().name().unwrap());
> ```

that is some excellent remote debugging, I would not have come up with that :+1: :tada: 

> Unfortunately rodio does not show any diagnostic messages when a non-default device is chosen.

Do you think rodio could emit a log message in that case, or would it be hard to detect?

**Comment by dvdsk** [comment]
> Do you think rodio could emit a log message in that case, or would it be hard to detect?

answering my own question: we can add a log message but it should largely be resolved in the next release when users migrate to using `OutputStreamBuilder::open_default_stream()?` Since they get an error if that fails.
